### ISSUE TITLE
ErrorException: PDO::quote(): Passing null to parameter #1 when a calendar entry is edited

### ISSUE THREAD

**Issue by LairdTurner** [ckulka/baikal-docker#77]
Hi!

I've just installed ckulka / baikal-docker.
If I create a new calendar and save it, everything works fine and I can connect to it and make entries,
but when I edit the calendar for example to edit the description.
This page is shown in the browser:

ErrorException: PDO::quote(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/baikal/Core/Frameworks/Flake/Core/Database.php:204
Stack trace:
#0 [internal function]: Baikal\Framework::exception_error_handler()
#1 /var/www/baikal/Core/Frameworks/Flake/Core/Database.php(204): PDO->quote()
#2 /var/www/baikal/Core/Frameworks/Flake/Core/Database.php(169): Flake\Core\Database->quote()
#3 /var/www/baikal/Core/Frameworks/Flake/Core/Database.php(181): Flake\Core\Database->fullQuote()
#4 /var/www/baikal/Core/Frameworks/Flake/Core/Database.php(81): Flake\Core\Database->fullQuoteArray()
#5 /var/www/baikal/Core/Frameworks/Flake/Core/Database.php(73): Flake\Core\Database->UPDATEquery()
#6 /var/www/baikal/Core/Frameworks/Flake/Core/Model/Db.php(101): Flake\Core\Database->exec_UPDATEquery()
#7 /var/www/baikal/Core/Frameworks/Baikal/Model/Calendar.php(72): Flake\Core\Model\Db->persist()
#8 /var/www/baikal/Core/Frameworks/Formal/Form.php(226): Baikal\Model\Calendar->persist()
#9 /var/www/baikal/Core/Frameworks/BaikalAdmin/Controller/User/Calendars.php(194): Formal\Form->execute()
#10 /var/www/baikal/Core/Frameworks/BaikalAdmin/Controller/User/Calendars.php(46): BaikalAdmin\Controller\User\Calendars->actionEdit()
#11 /var/www/baikal/Core/Frameworks/Flake/Core/Render/Container.php(62): BaikalAdmin\Controller\User\Calendars->execute()
#12 /var/www/baikal/Core/Frameworks/Flake/Controller/Page.php(88): Flake\Core\Render\Container->execute()
#13 /var/www/baikal/html/admin/index.php(90): Flake\Controller\Page->render()
#14 {main}

It looks like everything else works as expected I created users, adressbooks etc. and afterwards I was able to edit and save the settings.
I've installed ckulka/baikal:nginx via compose.

Nice regards

**Comment by LairdTurner** [comment]
I've installed the new image. It looks like it now works as expected! Thank you!
I'm looking foward to the new version of baikal!
