### ISSUE TITLE
PreconditionFailed

### ISSUE THREAD

**Issue by Lithimlin** [ckulka/baikal-docker#79]
Since about two days or so, I'm getting the following error which causes syncing my calendars with Thunderbird to fail:
```
2022/03/24 11:46:48 [error] 21#21: *1112 FastCGI sent in stderr: "PHP message: Sabre\DAV\Exception\PreconditionFailed: An If-None-Match header was specified, but the ETag matched (or * was specified). in /var/www/baikal/vendor/sabre/dav/lib/DAV/Server.php:1377
Stack trace:
#0 /var/www/baikal/vendor/sabre/dav/lib/DAV/Server.php(466): Sabre\DAV\Server->checkPreconditions()
#1 /var/www/baikal/vendor/sabre/dav/lib/DAV/Server.php(253): Sabre\DAV\Server->invokeMethod()
#2 /var/www/baikal/vendor/sabre/dav/lib/DAV/Server.php(321): Sabre\DAV\Server->start()
#3 /var/www/baikal/Core/Frameworks/Baikal/Core/Server.php(119): Sabre\DAV\Server->exec()
#4 /var/www/baikal/html/dav.php(69): Baikal\Core\Server->start()
#5 {main}" while reading response header from upstream, client: 172.18.0.3, server: _, request: "PUT /dav.php/calendars/<user>/default/87379da1-df01-4152-9008-6f16c1f5d2de.ics HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "my.domain.com"
172.18.0.3 - - [24/Mar/2022:11:46:48 +0000] "PUT /dav.php/calendars/<user>/default/87379da1-df01-4152-9008-6f16c1f5d2de.ics HTTP/1.1" 412 381 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:91.0) Gecko/20100101 Thunderbird/91.7.0" "<my-ip>"
172.18.0.3 - - [24/Mar/2022:11:46:48 +0000] "OPTIONS /dav.php/calendars/<user>/default/ HTTP/1.1" 200 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:91.0) Gecko/20100101 Thunderbird/91.7.0" "<my-ip>"
172.18.0.3 - - [24/Mar/2022:11:46:48 +0000] "REPORT /dav.php/calendars/<user>/default/ HTTP/1.1" 207 300 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:91.0) Gecko/20100101 Thunderbird/91.7.0" "<my-ip>"
```
I'm neither sure what this means nor why it's happening. Prehaps something changed internally with Thunderbird or Baikal? I'm not sure which of the two it is.
Syncing my calendar with my phone via DAVx5 seems to work fine though.

Thunderbird itself gives me the following message:
```
An error occurred when writing to the calendar Default! Please see below for more information.
Error:
MODIFICATION_FAILED
Description:
If you're seeing this message after snoozing or dismissing a reminder and this is for a calendar you do not want to add or edit events for, you can mark this calendar as read-only to avoid such experience in future. To do so, get to the calendar properties by right-clicking on this calendar in the list in the calendar or task view.
```
This just occurs during syncing, not when I'm interacting with events.

**Comment by ckulka** [comment]
Hi @Lithimlin, did you modify the event both on your phone and later in Thunderbird?

There weren't any changes in Baikal (January 2022) or Thunderbird (August 2021) as far as I can tell, so I'm suspicious if it's the same or similar issue as https://github.com/nextcloud/server/issues/14428. The suggested resolution is a "hard refresh" in Thunderbird (well, Evolution in their case, but doesn't matter here).

**Comment by Lithimlin** [comment]
It turned out to be a completely different problem with my setup and my IP. But thanks anyway for the help! That would have been my next course of action.
