### ISSUE TITLE
Error when changing Password

### ISSUE THREAD

**Issue by Jezz3** [ckulka/baikal-docker#93]
When i try to change the Password of a user account i doesnt work and i get an Error.
For another user account it is working.
Im running Baikal 0.9.1

```ErrorException: PDO::quote(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/baikal/Core/Frameworks/Flake/Core/Database.php:204```

Stack trace

```
#0 [internal function]: Baikal\Framework::exception_error_handler(8192, 'PDO::quote(): P...', '/var/www/baikal...', 204)
#1 /var/www/baikal/Core/Frameworks/Flake/Core/Database.php(204): PDO->quote(NULL)
#2 /var/www/baikal/Core/Frameworks/Flake/Core/Database.php(169): Flake\Core\Database->quote(NULL, 'principals')
#3 /var/www/baikal/Core/Frameworks/Flake/Core/Database.php(181): Flake\Core\Database->fullQuote(NULL, 'principals')
#4 /var/www/baikal/Core/Frameworks/Flake/Core/Database.php(81): Flake\Core\Database->fullQuoteArray(Array, 'principals', false)
#5 /var/www/baikal/Core/Frameworks/Flake/Core/Database.php(73): Flake\Core\Database->UPDATEquery('principals', 'id='4'', Array, false)
#6 /var/www/baikal/Core/Frameworks/Flake/Core/Model/Db.php(101): Flake\Core\Database->exec_UPDATEquery('principals', 'id='4'', Array)
#7 /var/www/baikal/Core/Frameworks/Baikal/Model/User.php(134): Flake\Core\Model\Db->persist()
#8 /var/www/baikal/Core/Frameworks/Formal/Form.php(226): Baikal\Model\User->persist()
#9 /var/www/baikal/Core/Frameworks/BaikalAdmin/Controller/Users.php(126): Formal\Form->execute()
#10 /var/www/baikal/Core/Frameworks/BaikalAdmin/Controller/Users.php(45): BaikalAdmin\Controller\Users->actionEdit()
#11 /var/www/baikal/Core/Frameworks/Flake/Core/Render/Container.php(62): BaikalAdmin\Controller\Users->execute()
#12 /var/www/baikal/Core/Frameworks/Flake/Controller/Page.php(88): Flake\Core\Render\Container->execute()
#13 /var/www/baikal/html/admin/index.php(90): Flake\Controller\Page->render()
#14 {main}
```

**Comment by Jezz3** [comment]
maybe related to #90 ?

**Comment by ckulka** [comment]
Hi @Jezz3, yes, looks like it's exactly the same cause - can you please open an issue with [sabre-io/Baikal](https://github.com/sabre-io/Baikal/issues)?

**Comment by Jezz3** [comment]
Ist gefixed in der neusten Version.
